### PR TITLE
cookie consent and anti adblock

### PR DESCRIPTION
**Pull request by gamfam1**

### CODE REVIEW

**Comment by ubgultra** [comment]
This is a iframe site, a adblock script won't help

**Comment by gamfam1** [comment]
> This is a iframe site, a adblock script won't help
> 
> Thanks for the support!

cookie consent is still needed

**Comment by ubgultra** [comment]
I'm not using cookies?

**Comment by gamfam1** [comment]
> I'm not using cookies?

is good to add

**Pull request closed without merging**
